
INSERT INTO game (
    name, type, distance, game_date, start_at, end_at, status,
    created_at, modified_at, participated_count, total_prize,
    first_place_prize, second_place_prize, third_place_prize,
    first_user_name, second_user_name, third_user_name
) VALUES
('주말 마무리 달리기', 'SPEED', 'TEN_KM_COURSE', DATE_SUB(CURDATE(), INTERVAL 2 DAY),
 DATE_ADD(DATE_SUB(CURDATE(), INTERVAL 2 DAY), INTERVAL 8 HOUR), DATE_ADD(DATE_SUB(CURDATE(), INTERVAL 2 DAY), INTERVAL 10 HOUR), 'FINISHED',
 DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 155, 150000, 120000, 20000, 10000, 'Winner1', 'RunnerUp1', 'ThirdPlace1'),


('지난 주 수요일 챌린지', 'HEARTBEAT', 'FIVE_KM_COURSE', DATE_SUB(CURDATE(), INTERVAL 5 DAY),
 DATE_ADD(DATE_SUB(CURDATE(), INTERVAL 5 DAY), INTERVAL 19 HOUR), DATE_ADD(DATE_SUB(CURDATE(), INTERVAL 5 DAY), INTERVAL 20 HOUR), 'FINISHED',
 DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), 210, 100000, 80000, 15000, 5000, 'Winner2', 'RunnerUp2', NULL),

('오래된 하프 마라톤', 'CADENCE', 'HALF_COURSE', DATE_SUB(CURDATE(), INTERVAL 10 DAY),
 DATE_ADD(DATE_SUB(CURDATE(), INTERVAL 10 DAY), INTERVAL 7 HOUR), DATE_ADD(DATE_SUB(CURDATE(), INTERVAL 10 DAY), INTERVAL 11 HOUR), 'FINISHED',
 DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), 95, 200000, 150000, 40000, 10000, 'Winner3', 'RunnerUp3', 'ThirdPlace3'),

('내일 새벽 공복 유산소', 'FLIGHT_TIME', 'FIVE_KM_COURSE', DATE_ADD(CURDATE(), INTERVAL 1 DAY),
 DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 1 DAY), INTERVAL 6 HOUR), DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 1 DAY), INTERVAL 7 HOUR), 'SCHEDULED',
 NOW(), NOW(), 5, 80000, 60000, 15000, 5000, NULL, NULL, NULL),

('다음 주 주말 풀코스', 'VERTICAL_OSCILLATION', 'FULL_COURSE', DATE_ADD(CURDATE(), INTERVAL 7 DAY),
 DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 7 DAY), INTERVAL 8 HOUR), DATE_ADD(DATE_ADD(CURDATE(), INTERVAL 7 DAY), INTERVAL 13 HOUR), 'SCHEDULED',
 DATE_SUB(NOW(), INTERVAL 1 DAY), NOW(), 2, 300000, 250000, 40000, 10000, NULL, NULL, NULL),

('오늘의 점심 번개런', 'POWER', 'FIVE_KM_COURSE', CURDATE(),
 DATE_SUB(NOW(), INTERVAL 1 HOUR), DATE_ADD(NOW(), INTERVAL 1 HOUR), 'PROGRESS',
 NOW(), NOW(), 55, 90000, 70000, 15000, 5000, NULL, NULL, NULL);
